on:
  push:
    tags:
      - '*'

name: CI/CD - Tag - Container Image Build and Webhook - Saas.Admin.Service

jobs:      
  build-image:
    name: Build and Publish Image
    uses: Azure/azure-saas/.github/workflows/template-container-image-build.yml@main
    with:
      image_to_push: asdk-admin
      tag_name: ${GITHUB_REF/refs\/tags\//}
      tag_latest: true

  # Add webhook jobs below here for each environment you want to automatically update
  # webhook-dev:
  #   name: Image Build Webhook - Dev
  #   needs: build-image
  #   if: needs.build-image.result == 'success'
  #   uses: Azure/azure-saas/.github/workflows/template-container-image-webhook.yml@main
  #   secrets:
  #     WEBHOOK_URL: ${{ secrets.ASDK_ADMIN_DEV_WEBHOOK_URL }}