# Builds any PR with target branch of "main". Creates app service slot with PR number and deploys built code
on:
  push:
    branches:
      - addcookiepolicy
  pull_request:
    types: [opened, synchronize, reopened]  
    branches:
      - main
    paths: 
      - "src/Saas.Application/**"
      - ".github/**"

name: Saas.Application.Web PR Build

jobs:
  build-and-deploy:
    # Utilizes re-usable template to build and deploy to app service slot
    uses: Azure/azure-saas/.github/workflows/template-pr-deploy.yml@main
    with:
      dotnet_version: '6.0.x'
      artifact_name: ${{ github.run_id }} 
      app_service_name: app-saas-app-asdk-dev-001
      app_service_resource_group_name: azure-saas-dev
      project_build_path: src/Saas.Application/Saas.Application.Web
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}