# On PR close, checks to see if PR was successfully merged. If yes, swaps slot into production and deletes PR slot. 
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "src/Saas.Admin/**"
      - ".github/**"

name: Saas.Admin.Service Swap Slot
jobs:
  build-and-deploy:
    # Utilizes re-usable template to build and deploy to app service slot
    uses: Azure/azure-saas/.github/workflows/template-pr-merge.yml@main
    with:
      app_service_name: app-asdk-admin-dev-001
      app_service_resource_group_name: azure-saas-dev  
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}